const computerScience = [
  {"subjectCode": "", "description": ""},
  {"subjectCode": "GNED 05", "description": "PURPOSIVE COMMUNICATION"},
  {"subjectCode": "FITT 1", "description": "MOVEMENT ENHANCEMENT"},
  {
    "subjectCode": "GNED 11",
    "description": "KONTEKSTWALISADONG KOMUNIKASYON SA FILIPINO",
  },
  {"subjectCode": "DCIT 22A", "description": "COMPUTER PROGRAMMING 1"},
  {"subjectCode": "COSC 50A", "description": "DISCRETE STRUCTURE"},
  {"subjectCode": "DCIT 21A", "description": "INTRODUCTION TO COMPUTING"},
  {"subjectCode": "GNED 02", "description": "ETHICS"},
  {"subjectCode": "GNED 01", "description": "ART APPRECIATION"},
  {"subjectCode": "GNED 03", "description": "MATHEMATICS IN THE MODERN WORLD"},
  {"subjectCode": "GNED 06", "description": "SCIENCE, TECHNOLOGY AND SOCIETY"},
  {"subjectCode": "GNED 12", "description": "DALUMAT NG/SA FILIPINO"},
  {"subjectCode": "DCIT23", "description": "COMPUTER PROGRAMMING II"},
  {"subjectCode": "ITEC50B", "description": "WEB SYSTEMS AND TECHNOLOGIES"},
  {"subjectCode": "FITT 2", "description": "FITNESS EXERCISES"},
  {"subjectCode": "MATH 1A", "description": "ANALYTIC GEOMETRY"},
  {"subjectCode": "COSC 55A", "description": "DISCRETE STRUCTURES II"},
  {"subjectCode": "DCIT 50LEC", "description": "OBJECT ORIENTED PROGRAMMING"},
  {"subjectCode": "DCIT 24LEC", "description": "INFORMATION MANAGEMENT"},
  {
    "subjectCode": "FITT 3",
    "description": "PHYSICAL ACTIVITIES TOWARDS HEALTH AND FITNESS 1",
  },
  {
    "subjectCode": "GNED 04",
    "description": "MGA BABASAHIN HINGGIL SA KASAYSAYAN NG PILIPINAS",
  },
  {"subjectCode": "COSC 60LEC", "description": "DIGITAL LOGIC DESIGN"},
  {
    "subjectCode": "INSY 50",
    "description": "FUNDAMENTALS OF INFORMATION SYSTEMS",
  },
  {"subjectCode": "COSC 60A", "description": "DIGITAL LOGIC DESIGN"},
  {
    "subjectCode": "DCIT55A",
    "description": "ADVANCED DATABASE MANAGEMENT SYSTEM",
  },
  {
    "subjectCode": "GNED 14",
    "description": "PANITIKANG PANLIPUNAN/SOSYEDAD AT LITERATURA",
  },
  {
    "subjectCode": "FITT 4",
    "description": "PHYSICAL ACTIVITIES TOWARDS HEALTH & FITNESS 2",
  },
  {"subjectCode": "COSC 65A", "description": "ARCHITECTURE AND ORGANIZATION"},
  {"subjectCode": "GNED 08", "description": "UNDERSTANDING THE SELF"},
  {"subjectCode": "DCIT 24A", "description": "INFORMATION MANAGEMENT"},
  {"subjectCode": "COSC 70A", "description": "SOFTWARE ENGINEERING I"},
  {"subjectCode": "MATH2C", "description": "CALCULUS"},
  {"subjectCode": "DCIT25", "description": "DATA STRUCTURES AND ALGORITHMS"},
  {"subjectCode": "DCIT 50", "description": "OBJECT ORIENTED PROGRAMMING"},
  {
    "subjectCode": "DCIT 26",
    "description": "APPLICATION DEVELOPMENT AND EMERGING TECHNOLOGIES",
  },
  {"subjectCode": "DCIT 65A", "description": "SOCIAL AND PROFESSIONAL ISSUES"},
  {"subjectCode": "COSC 85B", "description": "NETWORKS AND COMMUNICATION"},
  {"subjectCode": "MATH 3B", "description": "LINEAR ALGEBRA"},
  {"subjectCode": "COSC 75A", "description": "SOFTWARE ENGINEERING II"},
  {"subjectCode": "COSC 80B", "description": "OPERATING SYSTEMS"},
  {
    "subjectCode": "COSC 101",
    "description": "CS ELECTIVE 1 (COMPUTER GRAPHICS AND VISUAL COMPUTING)",
  },
  {"subjectCode": "MATH 4A", "description": "EXPERIMENTAL STATISTICS"},
  {
    "subjectCode": "COSC 90A",
    "description": "DESIGN AND ANALYSIS OF ALGORITHM"
  },
  {
    "subjectCode": "ITEC 85C",
    "description": "INFORMATION ASSURANCE AND SECURITY",
  },
  {"subjectCode": "COSC 95A", "description": "PROGRAMMING LANGUAGES"},
  {"subjectCode": "GNED 09", "description": "LIFE AND WORKS OF RIZAL"},
  {"subjectCode": "DCIT 60A", "description": "METHODS OF RESEARCH"},
  {
    "subjectCode": "COSC 106",
    "description": "CS ELECTIVE 2 (INTRODUCTION TO GAME DEVELOPMENT)",
  },
  {"subjectCode": "ITEC 80B", "description": "HUMAN COMPUTER INTERACTION"},
  {
    "subjectCode": "COSC 100A",
    "description": "AUTOMATA THEORY AND FORMAL LANGUAGES",
  },
  {"subjectCode": "COSC 200A", "description": "UNDERGRADUATE THESIS 1"},
  {
    "subjectCode": "COSC 111A",
    "description": "CS ELECTIVE 3 (INTERNET OF THINGS)",
  },
  {"subjectCode": "COSC 105", "description": "INTELLIGENT SYSTEMS"},
  {"subjectCode": "GNED 07", "description": "THE CONTEMPORARY WORLD"},
  {"subjectCode": "GNED 10", "description": "GENDER AND SOCIETY"},
  {
    "subjectCode": "COSC 110",
    "description": "NUMERICAL AND SYMBOLIC COMPUTATION",
  },
  {"subjectCode": "COSC 200BNEW", "description": "UNDERGRADUATE THESIS II"},
];
